version: '3'

services:
  ninjaPizza:
    container_name: ninjaPizzadev
    image: ninjapizzadev
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:80"
    depends_on:
      - mysqldev
    volumes: 
      - ./:/var/www/ninjapizza

  mysqldev:
    container_name: mysqldev
    image: mysql
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ninjaPizza
      MYSQL_USER: alvin
      MYSQL_PASSWORD: alvin123
    ports:
      - "6033:3306"

  phpmyadmindev:
    container_name: phpmyadmindev
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysqldev
      PMA_PORT: 3306
    ports:
      - "8899:80"
    depends_on:
      - mysqldev
    
